# Generated by Django 5.1.3 on 2024-11-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookservice', '0002_alter_book_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='authorId',
        ),
    ]
