# Generated by Django 5.1.3 on 2024-11-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookservice', '0003_rename_auther_book_authorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authorId',
        ),
        migrations.AddField(
            model_name='book',
            name='author_id',
            field=models.CharField(default='hai', max_length=36),
            preserve_default=False,
        ),
    ]
